### ISSUE TITLE
About the global offset

### ISSUE THREAD

**Issue by sjtuxcx** [garyzhao/SemGCN#12]
Hello, I noticed you remove the global offset in data_utils.py but it will lose the depth information. It will make a difference with others in the evaluating stage because you set the hip joint as the original point but not the camera. Your estimation will be easier because you don't need to estimate the depth.  I do not understand. Can you help me?

**Comment by garyzhao** [comment]
Hi @sjtuxcx 

Thanks for your interest in our work.

We follow the setting of [1] to do the prediction, which indicates that "Since we do not predict the global position of the 3d prediction, we zero-centre the 3d poses around the hip joint (in line with previous work and the standard protocol of Human3.6M)." (The first paragraph of Section 3.2 in [1])

In addition, if we evaluate the prediction by MPJPE (Protocol 1), the first step is to align the root (central hip) joint of the prediction and ground truth. I do not think predicting the global offset makes any difference here.

[1] Martinez et al. A simple yet effective baseline for 3d human pose estimation. ICCV 2017.
