### ISSUE TITLE
The results "43.8(61.1)" in Table-3 is different from that in Table-2 "43.8(60.8)" 

### ISSUE THREAD

**Issue by trumDog** [garyzhao/SemGCN#13]
Hi, I have found there is some difference between your results from Table 2 and 3 in the published paper, is there any difference?

Besides, the performance of the released code is still different from its paper, can you explain why, and what's the difference?

**Comment by garyzhao** [comment]
Hi @trumDog 

The 61.1 in Table 3 is a typo, which should be 60.8. We will fix it in a new version. Thanks for pointing out!

We use different training/evaluation sets in this repo (provided by [1]) and the original paper (provided by [2]), and that's why the performances are slightly different.

Best,
Long

[1] Martinez et al. A simple yet effective baseline for 3d human pose estimation. ICCV 2017.
[2] Zhou et al. Towards 3D Human Pose Estimation in the Wild: A weakly-supervised Approach. ICCV 2017

**Comment by trumDog** [comment]
@garyzhao Got it, thanks
