### ISSUE TITLE
A question of the 2D input and 3D ground truth

### ISSUE THREAD

**Issue by karenyun** [garyzhao/SemGCN#17]
Hi @garyzhao , thanks for your great work!
I have a question of the 2D input and 3D ground truth.

- 1) I find that you normalize the 2D pose position to (-1, 1) which corresponds to (0, w), why? 
- 2) Sorry I do not read the code of 3D part, are the 3D pose positions relative to the pivot? If yes, can I consider that they have been normalized?

Another question: does the Semgraph convolution can learn the position information? Or it only wants to use the neighborhood node information to learn the relationship between the 2D and 3D positions?

I am confused and hope you can give some suggestions, thanks very much!

**Comment by garyzhao** [comment]
Hi @karenyun 

Thanks for your interest in our work!

(i) The normalization makes convergence faster while training the network.
(ii) Yes.

Both (i) and (ii) are protocols presented in "A simple yet effective baseline for 3d human pose estimation" (ICCV 2017). Please check it for more details.

I think these two points are not conflicting. The graph convolution learns relevant 3D positions of joints from their 2D positions, and that's why we zero-center the 3D poses.

Best,
Long

**Comment by karenyun** [comment]
Hi @garyzhao , thanks very much!

Just another question, after subtracting the pivot for 3D pose, do you do other operations to normalize the coordinates to (-1, 1) as the 2D pose? :) I am confusing about it, sorry to bother again! Thanks!

**Comment by garyzhao** [comment]
> Hi @garyzhao , thanks very much!
> 
> Just another question, after subtracting the pivot for 3D pose, do you do other operations to normalize the coordinates to (-1, 1) as the 2D pose? :) I am confusing about it, sorry to bother again! Thanks!

We zero-center the 3D poses and convert them from (mm) to (m) and the results are in (-1, 1). No further operations are performed.

Best,
Long

**Comment by karenyun** [comment]
Thanks very much!
